# This migration was generated by the 
# rails new migration add_content_to_post command.
#

class AddContentToPost < ActiveRecord::Migration
  def self.up
    
    # This adds a string attribute called content to
    # the posts model (and a corresponding string field
    # called content to the posts table in the database.)
    
    # Running the rake db:migrate command will cause this
    # migration to be applied to the model and the database.
    
    add_column :posts, :content, :string

  end

  def self.down

    # This method reverses the changes created by the self.up
    # method - it removes the content field from the posts table,
    # and by implication the content attribute from the Post model.
    
    remove_column :posts, :content
  end
end
